version: '3.8'

services:
  backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NASA_API_KEY=${NASA_API_KEY}
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
